// Mocks generated by Mockito 5.0.10 from annotations
// in fluttdex/test/widget/home_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:fluttdex/models/pokemon.dart' as _i2;
import 'package:fluttdex/services/pokeapi_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakePokemon extends _i1.Fake implements _i2.Pokemon {}

/// A class which mocks [PokeApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokeApiService extends _i1.Mock implements _i3.PokeApiService {
  MockPokeApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Pokemon> pokemon(int? id) =>
      (super.noSuchMethod(Invocation.method(#pokemon, [id]),
              returnValue: Future<_i2.Pokemon>.value(_FakePokemon()))
          as _i4.Future<_i2.Pokemon>);
}
